sudo: required
services:
  - docker

# before_install:
#   - docker build -t alexlee27/react-test -f ./client/Dockerfile.dev ./client

# script:
#   - docker run -e CI=true alexlee27/react-test npm test

script:
  - docker build -t alexlee27/multi-client ./client
  - docker build -t alexlee27/multi-nginx ./nginx
  - docker build -t alexlee27/multi-server ./server
  - docker build -t alexlee27/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push alexlee27/multi-client
  - docker push alexlee27/multi-nginx
  - docker push alexlee27/multi-server
  - docker push alexlee27/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'first-m8-landingpage'
  env: 'firstm8landingpage-prod'
  bucket_name: 'elasticbeanstalk-us-east-2-205441520836'
  bucket_path: 'first-m8-landingpage'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY