version: '3'
services:
  prometheus:
    build:
      dockerfile: Dockerfile
      context: ./prometheus
    ports:
      - '9090:9090'
  landingpage:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '3000:3005'